### ISSUE TITLE
undefined is not object (evaluating 'PropTypes.array')

### ISSUE THREAD

**Issue by kentdev92** [bulenttastan/react-native-list-popover#20] opened 2017-08-08 10:23 UTC
undefined is not object (evaluating 'PropTypes.array')

<img width="379" alt="screen shot 2017-08-08 at 5 22 02 pm" src="https://user-images.githubusercontent.com/17426288/29067807-38b2a056-7c5e-11e7-9105-acc360793f98.png">

**Comment by igorbrandao** [comment] 2017-08-30 17:54
I'm getting this as well... The component is written in a deprecated lib that has finally been removed from react-native... we can just hope for a port from `React.createClass` to ES6 classes soon.

**Comment by hannahblair** [comment] 2017-10-09 00:03
+1

**Comment by bulenttastan** [comment] 2018-01-10 09:34
Caused by prop-types being moved to its own library:
https://reactjs.org/docs/typechecking-with-proptypes.html

I need to refactor the code to use React.Component and import PropTypes from the prop-types library.

**Comment by bulenttastan** [comment] 2018-01-15 04:22
Fixed in commit https://github.com/bulenttastan/react-native-list-popover/commit/2e7cde697505a9325ea332f014869c91292b5fea

**Closed as completed by bulenttastan** 2018-01-15 04:22 UTC
