### ISSUE TITLE
undefined is not an object (evaluating 'i.array')

### ISSUE THREAD

**Issue by lavarajallu** [bulenttastan/react-native-list-popover#19] opened 2017-02-14 05:39 UTC
**i  am using sample code your application popup menu  getting this errors and crash the app in x code:**

2017-02-14 11:05:57.154 [error][tid:com.facebook.react.JavaScript] undefined is not an object (evaluating 'i.array')
2017-02-14 11:05:57.157 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: undefined is not an object (evaluating 'i.array')
2017-02-14 11:05:57.160 [error][tid:com.facebook.react.JavaScript] Application Roger has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.
2017-02-14 11:05:57.165 Roger[2382:28654] *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: undefined is not an object (evaluating 'i.array')', reason: 'Unhandled JS Exception: undefined is not an object (evaluating 'i.array'), stack:
<unknown>@523:308
n@2:545
i@2:336
t@2:198
<unknown>@505:447
n@2:545
i@2:336
t@2:198
<unknown>@455:567
n@2:545
i@2:336
t@2:198
<unknown>@371:633
n@2:545
i@2:336
t@2:198
<unknown>@366:275
n@2:545
i@2:336
t@2:198
<unknown>@12:187
n@2:545
i@2:266
t@2:198
global code@679:9
'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000108fa6d85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010847cdeb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000108fa6cbd +[NSException raise:format:] + 205
	3   Roger                               0x000000010631ce94 RCTFatal + 393
	4   Roger                               0x0000000106315d3e -[RCTExceptionsManager reportFatalException:stack:exceptionId:] + 515
	5   CoreFoundation                      0x0000000108e8f5cc __invoking___ + 140
	6   CoreFoundation                      0x0000000108e8f41e -[NSInvocation invoke] + 286
	7   CoreFoundation                      0x0000000108f1ed26 -[NSInvocation invokeWithTarget:] + 54
	8   Roger                               0x0000000106319870 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 533
	9   Roger                               0x00000001063407d1 -[RCTBatchedBridge callNativeModule:method:params:] + 220
	10  Roger                               0x00000001063400b4 __33-[RCTBatchedBridge handleBuffer:]_block_invoke.357 + 447
	11  libdispatch.dylib                   0x000000010c203d9d _dispatch_call_block_and_release + 12
	12  libdispatch.dylib                   0x000000010c2243eb _dispatch_client_callout + 8
	13  libdispatch.dylib                   0x000000010c20a82c _dispatch_queue_drain + 2215
	14  libdispatch.dylib                   0x000000010c209d4d _dispatch_queue_invoke + 601
	15  libdispatch.dylib                   0x000000010c2243eb _dispatch_client_callout + 8
	16  libdispatch.dylib                   0x000000010c20cb2f _dispatch_root_queue_drain + 1829
	17  libdispatch.dylib                   0x000000010c20c405 _dispatch_worker_thread3 + 111
	18  libsystem_pthread.dylib             0x000000010c5784de _pthread_wqthread + 1129
	19  libsystem_pthread.dylib             0x000000010c576341 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by lavarajallu** [comment] 2017-02-14 05:40
**I am using this code :**
```


"use strict";
 
var React = require('react-native');
var ListPopover = require('react-native-list-popover');
var {
  AppRegistry,
  StyleSheet,
  Text,
  TouchableHighlight,
  View,
} = React;
var items = ["Item 1", "Item 2"];
 
class TestListPopover extends React.Component({
  getInitialState() {
    return {
      item: "Select Item",
      isVisible: false,
    };
  }
 
  showPopover() {
    this.setState({isVisible: true});
  }
  closePopover() {
    this.setState({isVisible: false});
  }
  setItem(item) {
    this.setState({item: item});
  }
 
  render() {
    return (
      <View style={styles.container}>
        <TouchableHighlight style={styles.button} onPress={this.showPopover.bind(this)}>
          <Text>{this.state.item}</Text>
        </TouchableHighlight>
 
        <ListPopover
          list={items}
          isVisible={this.state.isVisible}
          onClick={this.setItem}
          onClose={this.closePopover}/>
      </View>
    );
  }
});
 
var styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#532860',
  },
  button: {
    borderRadius: 4,
    padding: 10,
    marginLeft: 10,
    marginRight: 10,
    backgroundColor: "#B8C",
  },
});

module.exports = TestListPopover;
 
//AppRegistry.registerComponent('TestListPopover', () => TestListPopover);
```

**Comment by bulenttastan** [comment] 2018-01-10 09:36
dupe of https://github.com/bulenttastan/react-native-list-popover/issues/20

**Closed as completed** 2018-01-10 09:35 UTC
